language: java
sudo: enabled
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew clean codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
